"""Apply agent — applies pre-generated K8s manifests to a cluster and verifies.

This agent is the operational counterpart to the deploy agent. The deploy agent
generates manifests (like containerize generates Dockerfiles), and this agent
applies them (like build runs podman build). This separation keeps each agent
focused and reduces context overflow risk.
"""

import json
import logging
import re
from pathlib import Path

from langchain_core.language_models import BaseChatModel
from langchain_core.messages import AIMessage, HumanMessage, SystemMessage
from langgraph.prebuilt import create_react_agent

from autopoc.config import AutoPoCConfig, load_config
from autopoc.context import make_context_trimmer
from autopoc.llm import create_llm
from autopoc.state import PoCPhase, PoCState
from autopoc.tools.file_tools import list_files, read_file
from autopoc.tools.k8s_tools import (
    kubectl_apply,
    kubectl_apply_from_string,
    kubectl_create_namespace,
    kubectl_get,
    kubectl_get_service_url,
    kubectl_logs,
    kubectl_wait_for_rollout,
)

logger = logging.getLogger(__name__)

APPLY_PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "apply.md"

# Tools for the apply agent — cluster operations + file reading (no writing)
APPLY_TOOLS = [
    kubectl_create_namespace,
    kubectl_apply,
    kubectl_apply_from_string,
    kubectl_get,
    kubectl_logs,
    kubectl_wait_for_rollout,
    kubectl_get_service_url,
    read_file,
    list_files,
]


def _extract_final_ai_content(messages: list) -> str:
    """Extract text content from the last AIMessage with non-empty content."""
    for msg in reversed(messages):
        if not isinstance(msg, AIMessage):
            continue
        content = msg.content
        if isinstance(content, list):
            content = "".join(
                part["text"] if isinstance(part, dict) and "text" in part else str(part)
                for part in content
            )
        if isinstance(content, str) and content.strip():
            return content
    return ""


def _parse_apply_output(raw_output: str, messages: list) -> dict:
    """Parse the apply agent's output to extract resources and routes.

    Tries to find a JSON object in the output. Falls back to extracting
    from tool call results in the message history.
    """
    # Try to parse JSON from the final message
    text = raw_output.strip()
    match = re.search(r"\{.*\}", text, re.DOTALL)
    if match:
        try:
            data = json.loads(match.group(0))
            return {
                "deployed_resources": data.get("deployed_resources", []),
                "routes": data.get("routes", []),
                "error": data.get("error"),
            }
        except json.JSONDecodeError:
            pass

    # Fallback: extract from tool calls in messages
    deployed_resources = []
    routes = []

    for msg in messages:
        if hasattr(msg, "tool_calls"):
            for tool_call in msg.tool_calls:
                if tool_call["name"] == "kubectl_apply":
                    manifest_path = tool_call["args"].get("manifest_path", "")
                    if manifest_path:
                        if "deployment" in manifest_path:
                            resource_name = Path(manifest_path).stem.replace("-deployment", "")
                            deployed_resources.append(f"deployment/{resource_name}")
                        elif "service" in manifest_path:
                            resource_name = Path(manifest_path).stem.replace("-service", "")
                            deployed_resources.append(f"service/{resource_name}")
                        elif "namespace" in manifest_path:
                            resource_name = Path(manifest_path).stem.replace("-namespace", "")
                            deployed_resources.append(f"namespace/{resource_name}")
                        elif "job" in manifest_path:
                            resource_name = Path(manifest_path).stem.replace("-job", "")
                            deployed_resources.append(f"job/{resource_name}")

        # Check for URLs in tool results
        if hasattr(msg, "content") and isinstance(msg.content, str):
            content = msg.content
            if content.startswith("http://") or content.startswith("https://"):
                routes.append(content.strip())

    return {
        "deployed_resources": deployed_resources,
        "routes": routes,
        "error": None,
    }


async def apply_agent(
    state: PoCState,
    app_config: AutoPoCConfig | None = None,
    llm: BaseChatModel | None = None,
) -> PoCState:
    """Apply K8s manifests to the cluster and verify deployment.

    Args:
        state: Current pipeline state with manifests already generated by deploy agent
        app_config: Configuration (optional, loads from env if not provided)
        llm: Language model (optional, creates default if not provided)

    Returns:
        Updated state with deployed_resources and routes populated
    """
    logger.info("=== Apply Phase ===")

    if not app_config:
        app_config = load_config()

    if not llm:
        llm = create_llm()

    system_prompt = APPLY_PROMPT_PATH.read_text()

    # Check prerequisites
    project_name = state.get("project_name", "unknown")
    local_clone_path = state.get("local_clone_path", "")
    components = state.get("components", [])
    built_images = state.get("built_images", [])
    previous_error = state.get("error")
    deploy_retries = state.get("deploy_retries", 0)
    poc_infrastructure = state.get("poc_infrastructure")

    if not components and not built_images:
        logger.error("No components or built images to apply — nothing to deploy")
        return {
            "current_phase": PoCPhase.APPLY,
            "deployed_resources": [],
            "routes": [],
            "error": (
                "No components or built images. "
                "Check earlier pipeline stages (intake, containerize, build)."
            ),
        }

    k8s_dir = str(Path(local_clone_path) / "kubernetes")

    user_message = f"""Apply the Kubernetes manifests to the cluster.

Project: {project_name}
Namespace: {project_name}
Repository path: {local_clone_path}
Manifests directory: {k8s_dir}

Components:
"""

    for component in components:
        comp_name = component.get("name", "unknown")
        matching_image = next((img for img in built_images if comp_name in img), None)
        user_message += f"\n- {comp_name}: image={matching_image or 'NOT FOUND'}"
        port = component.get("port")
        if port:
            user_message += f", port={port}"

    # Include deployment model info
    if poc_infrastructure:
        deployment_model = poc_infrastructure.get("deployment_model", "deployment")
        listens_on_port = poc_infrastructure.get("listens_on_port", True)
        test_strategy = poc_infrastructure.get("test_strategy", "http")
        user_message += f"\n\n**Deployment model:** {deployment_model}"
        user_message += f"\n**Listens on port:** {listens_on_port}"
        user_message += f"\n**Test strategy:** {test_strategy}"

    # If this is a retry, include the previous error
    if previous_error and deploy_retries > 0:
        user_message += (
            f"\n\n**PREVIOUS APPLY ATTEMPT FAILED (retry {deploy_retries}):**\n"
            f"{previous_error}\n\n"
            f"Please re-apply and verify. If the manifests need fixing, return an error "
            f"and the pipeline will route back to the deploy agent."
        )

    user_message += (
        "\n\nList the files in the kubernetes/ directory, then apply them in order. "
        "Wait for rollouts, verify pods, and get service URLs."
    )

    # Create agent
    agent = create_react_agent(
        model=llm,
        tools=APPLY_TOOLS,
        pre_model_hook=make_context_trimmer(),
    )

    logger.info("Invoking apply agent for %d components", len(components))

    try:
        result = await agent.ainvoke(
            {
                "messages": [
                    SystemMessage(content=system_prompt),
                    HumanMessage(content=user_message),
                ]
            },
            config={"recursion_limit": 40},
        )

        messages = result.get("messages", [])
        raw_output = _extract_final_ai_content(messages)
        parsed = _parse_apply_output(raw_output, messages)

        deployed_resources = parsed["deployed_resources"]
        routes = parsed["routes"]
        error = parsed.get("error")

        # If we didn't extract resources and there's no error, infer from components
        if not deployed_resources and not error:
            for component in components:
                comp_name = component.get("name", "")
                deployed_resources.append(f"deployment/{comp_name}")
                if component.get("port"):
                    deployed_resources.append(f"service/{comp_name}")

        if error:
            logger.warning("Apply agent reported error: %s", error)
            current_retries = state.get("deploy_retries", 0)
            return {
                "current_phase": PoCPhase.APPLY,
                "deployed_resources": deployed_resources,
                "routes": routes,
                "error": error,
                "deploy_retries": current_retries + 1,
            }

        logger.info(
            "Apply complete: %d resources, %d routes",
            len(deployed_resources),
            len(routes),
        )

        return {
            "current_phase": PoCPhase.APPLY,
            "deployed_resources": deployed_resources,
            "routes": routes,
            "error": None,
        }

    except Exception as e:
        logger.error("Apply failed: %s", e, exc_info=True)
        current_retries = state.get("deploy_retries", 0)

        return {
            "current_phase": PoCPhase.APPLY,
            "deployed_resources": [],
            "routes": [],
            "error": f"Apply failed: {e}",
            "deploy_retries": current_retries + 1,
        }
