"""Build agent — builds and pushes container images.

This agent uses a pluggable BuildStrategy to build Dockerfile.ubi files
generated by the containerize agent. Supported strategies:
- podman: Shells out to local podman CLI (default).
- openshift: Uses OpenShift BuildConfig / oc start-build for on-cluster builds.

If a build fails, it uses an LLM to generate a brief diagnosis to aid the
retry loop. For "command not found" errors, it also asks the LLM how to
install the missing command and patches the Dockerfile directly.
"""

import logging
import re
from pathlib import Path

from langchain_core.messages import HumanMessage, SystemMessage

from autopoc.config import AutoPoCConfig
from autopoc.llm import create_llm
from autopoc.state import PoCPhase, PoCState
from autopoc.tools.build_strategy import BuildStrategy, PodmanBuildStrategy, get_build_strategy
from autopoc.tools.quay_tools import QuayClient

logger = logging.getLogger(__name__)

# Track which registries we've logged into during this session
_logged_in_registries: set[str] = set()


def _is_permanent_failure(error_msg: str) -> bool:
    """Detect if a build/push error is permanent (won't be fixed by Dockerfile changes).

    Permanent failures include:
    - Authentication/authorization errors
    - Network/registry unreachable
    - Missing podman binary
    - Disk full
    - Invalid registry URL

    Returns:
        True if the error is permanent and retrying won't help
    """
    error_lower = error_msg.lower()

    # Authentication/authorization failures
    if any(
        phrase in error_lower
        for phrase in [
            "unauthorized",
            "authentication required",
            "authentication failed",
            "login required",
            "access denied",
            "forbidden",
            "credentials",
            "401 unauthorized",
            "403 forbidden",
        ]
    ):
        return True

    # Network/connectivity issues
    if any(
        phrase in error_lower
        for phrase in [
            "connection refused",
            "network unreachable",
            "no route to host",
            "could not resolve host",
            "dial tcp",
            "i/o timeout",
        ]
    ):
        return True

    # Missing host tools or system errors
    # NOTE: "command not found" inside a Dockerfile RUN step (e.g., "sh: vitepress:
    # command not found") is a Dockerfile bug, NOT a permanent host failure.
    # Only treat it as permanent if it's about podman itself being missing.
    if any(
        phrase in error_lower
        for phrase in [
            "no such file or directory: 'podman'",
            "disk quota exceeded",
            "no space left on device",
        ]
    ):
        return True

    # "command not found" is permanent only if it's about the build tool itself,
    # not about a command inside a Dockerfile RUN step.
    # A Dockerfile "command not found" will appear inside "while running runtime"
    # or "building at STEP" context — that's a retryable Dockerfile issue.
    if "command not found" in error_lower:
        # If the error mentions a Dockerfile STEP, it's a build issue (retryable)
        if "step " in error_lower or "while running runtime" in error_lower:
            return False
        # Otherwise it's likely a missing host tool (permanent)
        return True

    return False


def _parse_missing_command(error_log: str) -> tuple[str | None, str | None, str | None]:
    """Parse a 'command not found' build error to extract details.

    Returns:
        (missing_command, failing_step, base_image) or (None, None, None) if not found.
    """
    error_lower = error_log.lower()
    if "command not found" not in error_lower:
        return None, None, None

    # Extract the missing command name
    # Patterns: "bun: command not found", "sh: line 1: bun: command not found"
    cmd_match = re.search(
        r"(?:sh:\s*(?:line \d+:\s*)?)?(\S+):\s*(?:command\s+)?not\s+found",
        error_log,
        re.IGNORECASE,
    )
    missing_cmd = cmd_match.group(1) if cmd_match else None

    # Extract the failing STEP
    step_match = re.search(
        r'(?:STEP \d+/\d+:\s*)(RUN\s+.+?)(?:\n|$)',
        error_log,
    )
    failing_step = step_match.group(1).strip() if step_match else None

    # Extract base image from the build log
    base_match = re.search(
        r'STEP 1/\d+:\s*FROM\s+(\S+)',
        error_log,
    )
    base_image = base_match.group(1) if base_match else None

    return missing_cmd, failing_step, base_image


async def _fix_missing_command_in_dockerfile(
    dockerfile_path: Path,
    missing_cmd: str,
    failing_step: str | None,
    base_image: str | None,
) -> bool:
    """Ask the LLM how to install a missing command and patch the Dockerfile.

    Makes a focused LLM call to get the install command, then injects it
    into the Dockerfile before the failing step.

    Args:
        dockerfile_path: Path to the Dockerfile to patch.
        missing_cmd: The command that was not found (e.g. "bun", "uv").
        failing_step: The RUN line that failed (e.g. "RUN bun install").
        base_image: The base image (e.g. "registry.access.redhat.com/ubi9/nodejs-22").

    Returns:
        True if the Dockerfile was patched, False otherwise.
    """
    if not dockerfile_path.exists():
        return False

    content = dockerfile_path.read_text(encoding="utf-8")

    base_desc = f" (base image: {base_image})" if base_image else ""
    llm = create_llm()

    prompt = (
        f"The command `{missing_cmd}` is not found in a container{base_desc}.\n"
        f"What is the single Dockerfile RUN command to install it?\n"
        f"Reply with ONLY the RUN line, nothing else. No explanation.\n"
        f"Example format: RUN npm install -g bun\n"
        f"Example format: RUN pip install uv\n"
        f"Example format: RUN dnf install -y make && dnf clean all"
    )

    try:
        response = await llm.ainvoke([
            SystemMessage(content="You are a Dockerfile expert. Reply with only the requested RUN command."),
            HumanMessage(content=prompt),
        ])
        install_line = response.content.strip()

        # Validate: must start with RUN
        if not install_line.upper().startswith("RUN "):
            # Try to extract a RUN line from the response
            run_match = re.search(r"^(RUN\s+.+)$", install_line, re.MULTILINE | re.IGNORECASE)
            if run_match:
                install_line = run_match.group(1)
            else:
                logger.warning(
                    "LLM response for installing '%s' was not a valid RUN line: %s",
                    missing_cmd,
                    install_line[:200],
                )
                return False

        # Clean up: remove markdown code fences if present
        install_line = install_line.strip("`").strip()
        if install_line.startswith("dockerfile"):
            install_line = install_line[len("dockerfile"):].strip()

        logger.info(
            "LLM suggests installing '%s' with: %s",
            missing_cmd,
            install_line,
        )

        # Find the failing step in the Dockerfile and insert the install before it
        lines = content.split("\n")
        fixed_lines = []
        inserted = False

        for line in lines:
            # Match the failing step (case-insensitive, whitespace-flexible)
            if (
                not inserted
                and failing_step
                and line.strip().upper().startswith("RUN ")
                and missing_cmd.lower() in line.lower()
            ):
                fixed_lines.append(install_line)
                inserted = True
                logger.info(
                    "Inserted install command before: %s",
                    line.strip()[:80],
                )

            fixed_lines.append(line)

        # If we couldn't find the exact failing step, insert before the first
        # RUN that's not a package manager install (dnf/microdnf/apt/yum)
        if not inserted:
            fixed_lines = []
            for line in lines:
                stripped = line.strip().upper()
                if (
                    not inserted
                    and stripped.startswith("RUN ")
                    and not any(
                        pkg in stripped
                        for pkg in ("DNF ", "MICRODNF ", "APT ", "YUM ", "INSTALL -G")
                    )
                ):
                    fixed_lines.append(install_line)
                    inserted = True
                    logger.info(
                        "Inserted install command before first non-package RUN: %s",
                        line.strip()[:80],
                    )
                fixed_lines.append(line)

        if inserted:
            dockerfile_path.write_text("\n".join(fixed_lines), encoding="utf-8")
            return True

        logger.warning("Could not find insertion point for install command in Dockerfile")
        return False

    except Exception as e:
        logger.warning("Failed to get install command for '%s': %s", missing_cmd, e)
        return False


def _parse_not_found_packages(error_log: str) -> list[str]:
    """Parse package-not-found errors from any package manager.

    Supports: npm, pip, Go modules, Cargo (Rust), RubyGems, Maven/Gradle.

    Returns:
        List of package names that don't exist in the registry.
    """
    packages = []

    def _add(pkg: str) -> None:
        if pkg and pkg not in packages:
            packages.append(pkg)

    # --- npm / yarn / pnpm ---
    # "'@types/vite@*' is not in this registry"
    for m in re.finditer(r"'([^'@]+(?:@[^']+)?)(?:@[^']*)?' is not in this registry", error_log):
        _add(m.group(1))
    # "404 Not Found - GET https://registry.npmjs.org/<pkg> - Not found"
    for m in re.finditer(r"404 Not Found - GET https?://[^\s]+/([^\s]+)\s*-\s*Not found", error_log):
        _add(m.group(1).replace("%2f", "/").replace("%2F", "/"))

    # --- pip ---
    # "No matching distribution found for <pkg>"
    for m in re.finditer(r"No matching distribution found for ([^\s,]+)", error_log):
        _add(m.group(1))
    # "Could not find a version that satisfies the requirement <pkg>"
    for m in re.finditer(r"Could not find a version that satisfies the requirement ([^\s,;(]+)", error_log):
        _add(m.group(1))

    # --- Go modules ---
    # "module <pkg> not found" or "cannot find module providing package <pkg>"
    for m in re.finditer(r"module ([^\s:]+): not found", error_log):
        _add(m.group(1))
    for m in re.finditer(r"cannot find module providing package ([^\s:]+)", error_log):
        _add(m.group(1))

    # --- Cargo (Rust) ---
    # "no matching package named `<pkg>` found"
    for m in re.finditer(r"no matching package named `([^`]+)` found", error_log):
        _add(m.group(1))
    # "failed to select a version for the requirement `<pkg> = ...`"
    for m in re.finditer(r"failed to select a version for the requirement `([^`\s=]+)", error_log):
        _add(m.group(1))

    # --- RubyGems ---
    # "Could not find gem '<pkg>'"
    for m in re.finditer(r"Could not find gem ['\"]([^'\"]+)['\"]", error_log):
        _add(m.group(1))

    # --- Maven / Gradle ---
    # "Could not resolve <group>:<artifact>:<version>"
    for m in re.finditer(r"Could not resolve ([^\s]+:[^\s]+:[^\s]+)", error_log):
        _add(m.group(1))
    # "Could not find artifact <group>:<artifact>"
    for m in re.finditer(r"Could not find artifact ([^\s]+)", error_log):
        _add(m.group(1))

    return packages


async def build_agent(
    state: PoCState,
    *,
    app_config: AutoPoCConfig | None = None,
    quay_client: QuayClient | None = None,
    build_strategy: BuildStrategy | None = None,
    llm=None,
) -> dict:
    """Build and push container images for all components.

    Args:
        state: Current pipeline state.
        app_config: Optional config override.
        quay_client: Optional Quay client override.
        build_strategy: Optional BuildStrategy override. If None, created from config.
        llm: Optional LLM override.

    Returns:
        Partial state update.
    """
    project_name = state["project_name"]
    components = state.get("components", [])

    logger.info("Starting build phase for %d component(s)", len(components))

    if app_config is None:
        from autopoc.config import load_config

        app_config = load_config()

    owns_client = quay_client is None
    if quay_client is None:
        quay_client = QuayClient(app_config)

    # Create build strategy from config if not provided
    if build_strategy is None:
        build_strategy = get_build_strategy(app_config)

    logger.info("Using build strategy: %s", type(build_strategy).__name__)

    clone_path = state.get("local_clone_path")
    if not clone_path:
        raise ValueError("Cannot build: local_clone_path is missing from state")

    repo_dir = Path(clone_path)
    built_images = list(state.get("built_images", []))
    retries = state.get("build_retries", 0)

    # Ensure we're logged in to the registry
    # Extract registry host from URL
    registry_url = app_config.quay_registry
    if "://" in registry_url:
        registry_host = registry_url.split("://", 1)[1]
    else:
        registry_host = registry_url

    # Check if we need to login (only once per session)
    global _logged_in_registries
    if registry_host not in _logged_in_registries:
        try:
            logger.info("Logging in to registry: %s", registry_host)
            tls_verify = not registry_url.startswith("http://")

            # Login to the registry
            # Robot accounts use their username (e.g. 'myuser+robotname')
            # OAuth tokens use '$oauthtoken' as the username (Quay convention)
            registry_username = app_config.quay_username or "$oauthtoken"
            build_strategy.login(
                registry=registry_host,
                username=registry_username,
                password=app_config.quay_token,
                tls_verify=tls_verify,
            )
            _logged_in_registries.add(registry_host)
        except Exception as e:
            error_msg = str(e)
            logger.error("Failed to login to registry: %s", error_msg)
            return {
                "current_phase": PoCPhase.BUILD,
                "error": f"Registry authentication failed: {error_msg}\n\n"
                "This is a permanent failure. Please check your QUAY_TOKEN in .env",
                "build_retries": retries,  # Don't increment - this isn't worth retrying
                "components": components,
                "built_images": built_images,
            }

    # Check if any component actually has a Dockerfile to build.
    # If containerize failed (e.g. poc_plan_error), no component will have a
    # dockerfile_ubi_path.  Propagate the upstream error instead of silently
    # declaring success.
    incoming_error = state.get("error")
    has_any_dockerfile = any(c.get("dockerfile_ubi_path") for c in components)
    if not has_any_dockerfile:
        msg = (
            incoming_error
            or "No Dockerfile.ubi files were generated — nothing to build. "
            "This usually means the containerize phase failed."
        )
        logger.error("Build skipped: %s", msg[:200])
        return {
            "current_phase": PoCPhase.BUILD,
            "error": msg,
            "build_retries": retries,
            "components": components,
            "built_images": built_images,
        }

    try:
        for comp in components:
            comp_name = comp["name"]

            # Skip if we already built this image in a previous attempt
            # or if the component lacks a dockerfile.
            dockerfile = comp.get("dockerfile_ubi_path")
            if not dockerfile:
                logger.info("Skipping build for %s: no dockerfile_ubi_path", comp_name)
                continue

            repo_name = f"{project_name}-{comp_name}"
            # Ensure Quay repo exists
            image_ref = quay_client.ensure_repo(app_config.quay_org, repo_name)

            # Determine image tag based on container_fix_action
            container_fix_action = state.get("container_fix_action")
            if container_fix_action == "experiment":
                exp_counter = state.get("experiment_tag_counter", 0) + 1
                tag = f"experiment-{exp_counter}"
                logger.info(
                    "Experiment mode: tagging %s as :%s (keeping :latest clean)",
                    comp_name,
                    tag,
                )
            else:
                tag = "latest"

            full_tag = f"{image_ref}:{tag}"

            if full_tag in built_images:
                logger.info("Skipping build for %s: already built", comp_name)
                continue

            logger.info("Building image for %s: %s", comp_name, full_tag)

            try:
                # If the registry is HTTP (like local E2E), disable TLS verify
                tls_verify = not app_config.quay_registry.startswith("http://")

                # Verify the Dockerfile exists before attempting the build
                dockerfile_path = repo_dir / dockerfile
                if not dockerfile_path.exists():
                    # Log what files are actually in the directory for debugging
                    existing = [
                        str(p.relative_to(repo_dir))
                        for p in repo_dir.rglob("Dockerfile*")
                    ]
                    logger.error(
                        "Dockerfile not found at %s. "
                        "Dockerfiles in repo: %s",
                        dockerfile_path,
                        existing or "(none)",
                    )
                    raise RuntimeError(
                        f"Dockerfile not found: {dockerfile_path}\n"
                        f"The containerize agent may have failed to write it, "
                        f"or a git operation (stash/branch switch) removed it.\n"
                        f"Dockerfiles found in repo: {existing or '(none)'}"
                    )

                # Build the image
                build_strategy.build(
                    context_path=str(repo_dir),
                    dockerfile=str(dockerfile_path),
                    tag=full_tag,
                    tls_verify=tls_verify,
                )
                logger.info("Build successful for %s", comp_name)

                # Push the image (no-op for OpenShift builds, which push during build)
                logger.info("Pushing image %s", full_tag)
                build_strategy.push(image=full_tag, tls_verify=tls_verify)

                # Load image into kind cluster for local E2E testing (podman only)
                # This makes the image available in kind's cache so it doesn't need to pull
                # from the registry (which may be localhost and unreachable from inside kind)
                if isinstance(build_strategy, PodmanBuildStrategy):
                    try:
                        import shutil

                        from autopoc.tools.podman_tools import kind_load_image

                        if shutil.which("kind"):
                            logger.info("Loading image into kind cluster for local E2E testing")
                            kind_load_image(full_tag, cluster_name="autopoc-e2e")
                            logger.info("Image loaded into kind cluster")
                    except Exception as kind_err:
                        # Don't fail the build if kind loading fails
                        # This is optional and only for local E2E testing
                        logger.warning(
                            "Failed to load image into kind cluster (non-fatal): %s", kind_err
                        )

                built_images.append(full_tag)
                comp["image_name"] = full_tag

            except Exception as e:
                error_log = str(e)
                logger.error(
                    "Build failed for %s: %s", comp_name, error_log[:500]
                )  # Log first 500 chars

                # Dockerfile not found is a containerize failure, not a build failure.
                # Don't increment build_retries — preserve retry budget for real build errors.
                is_dockerfile_missing = "Dockerfile not found:" in error_log
                if is_dockerfile_missing:
                    logger.warning(
                        "Dockerfile missing for %s — not counting as build retry "
                        "(containerize agent needs to generate it)",
                        comp_name,
                    )

                # Check if this is a permanent failure
                if _is_permanent_failure(error_log):
                    logger.error("Detected permanent failure - will not retry")
                    return {
                        "current_phase": PoCPhase.BUILD,
                        "error": f"Build failed for component '{comp_name}' with a permanent error.\n"
                        f"This error cannot be fixed by retrying or modifying the Dockerfile.\n\n"
                        f"Error:\n{error_log}\n\n"
                        f"Common causes:\n"
                        f"- Registry authentication failure (check QUAY_TOKEN)\n"
                        f"- Network connectivity issues\n"
                        f"- Registry not reachable\n"
                        f"- Missing system tools",
                        "build_retries": retries,  # Don't increment for permanent failures
                        "components": components,
                        "built_images": built_images,
                    }

                # Diagnose with LLM for fixable errors
                # IMPORTANT: Always create a fresh LLM instance for diagnosis to avoid
                # context overflow. The passed-in llm may have accumulated 200k+ tokens
                # from previous agents (intake, containerize, etc.)
                diagnosis_llm = create_llm()

                # Truncate error log to avoid context overflow
                # Large repos can generate massive build logs (100k+ tokens)
                # Keep last 10k chars which usually has the most relevant error
                max_error_length = 10000
                truncated_error = error_log
                if len(error_log) > max_error_length:
                    truncated_error = (
                        f"[Error log truncated - showing last {max_error_length} characters]\n\n"
                        f"...{error_log[-max_error_length:]}"
                    )
                    logger.info(
                        "Truncated error log from %d to %d characters for LLM diagnosis",
                        len(error_log),
                        len(truncated_error),
                    )

                sys_msg = SystemMessage(
                    content="You are an expert container build debugger. "
                    "Analyze the following podman build error and provide a concise, "
                    "1-2 sentence diagnosis of what went wrong and how to fix the Dockerfile."
                )
                user_msg = HumanMessage(
                    content=f"Build failed for {dockerfile}:\n\n{truncated_error}"
                )

                diagnosis_result = await diagnosis_llm.ainvoke([sys_msg, user_msg])
                diagnosis = diagnosis_result.content

                # If the error is "command not found", try to patch the Dockerfile
                # directly by asking the LLM for the install command.
                # This is more reliable than hoping the containerize retry will
                # generate a correct Dockerfile — it often reproduces the same bug.
                missing_cmd, failing_step, base_image = _parse_missing_command(error_log)
                if missing_cmd:
                    logger.info(
                        "Detected missing command '%s' — attempting to patch Dockerfile",
                        missing_cmd,
                    )
                    patched = await _fix_missing_command_in_dockerfile(
                        dockerfile_path,
                        missing_cmd,
                        failing_step,
                        base_image,
                    )
                    if patched:
                        logger.info(
                            "Patched Dockerfile to install '%s' — "
                            "retrying build immediately with patched Dockerfile",
                            missing_cmd,
                        )
                        # Retry the build immediately with the patched Dockerfile.
                        # Don't return to the graph loop (containerize would overwrite
                        # the patch). This uses one retry count but avoids the
                        # containerize → build round-trip.
                        try:
                            build_strategy.build(
                                context_path=str(repo_dir),
                                dockerfile=str(dockerfile_path),
                                tag=full_tag,
                                tls_verify=tls_verify,
                            )
                            logger.info("Build successful for %s after installing '%s'", comp_name, missing_cmd)
                            build_strategy.push(image=full_tag, tls_verify=tls_verify)
                            built_images.append(full_tag)
                            comp["image_name"] = full_tag
                            continue  # Move to the next component
                        except Exception as retry_err:
                            logger.warning(
                                "Build still failed after installing '%s': %s",
                                missing_cmd,
                                str(retry_err)[:300],
                            )
                            # Fall through to normal error handling below

                # Truncate error for state storage (containerize agent will see this)
                # Keep it concise so it doesn't bloat the state
                error_for_state = error_log
                if len(error_log) > 2000:
                    error_for_state = f"...{error_log[-2000:]}"

                error_state = (
                    f"Build failed for component '{comp_name}' using Dockerfile '{dockerfile}'.\n"
                    f"Diagnosis:\n{diagnosis}\n\n"
                    f"Raw Error:\n{error_for_state}"
                )

                # Enrich the error with explicit instructions about non-existent packages.
                # Without this, the LLM will keep hallucinating the same package names.
                bad_packages = _parse_not_found_packages(error_log)
                if bad_packages:
                    pkg_list = ", ".join(f"`{p}`" for p in bad_packages)
                    error_state += (
                        f"\n\n**CRITICAL: The following packages DO NOT EXIST in the "
                        f"registry and MUST be removed entirely: {pkg_list}. "
                        f"Do NOT include them in any install command. "
                        f"They were hallucinated — they are not real packages.**"
                    )

                return {
                    "current_phase": PoCPhase.BUILD,
                    "error": error_state,
                    # Don't increment retries for missing Dockerfiles — that's a
                    # containerize failure, not a build failure. Preserve retry
                    # budget for actual build errors.
                    "build_retries": retries if is_dockerfile_missing else retries + 1,
                    "components": components,  # To persist any image_name updates from successful builds
                    "built_images": built_images,
                }

        logger.info("All builds completed successfully")
        result_state = {
            "current_phase": PoCPhase.BUILD,
            "error": None,
            "components": components,
            "built_images": built_images,
        }
        # If we used an experiment tag, update the counter
        container_fix_action = state.get("container_fix_action")
        if container_fix_action == "experiment":
            result_state["experiment_tag_counter"] = state.get("experiment_tag_counter", 0) + 1
        # Clear the action so deploy picks up the new image cleanly
        result_state["container_fix_action"] = None
        return result_state

    finally:
        if owns_client:
            quay_client.close()
